### ISSUE TITLE
Merge Vanilla and Uppercase Propachi version

### ISSUE THREAD

**Issue by bwiernik** [Juris-M/propachi-vanilla#1]
It would be nice to have the uppercase option as a toggle-able preference in a single Propachi plugin. I'd be happy to work on setting up a preference pane and such for that. Where in the two plugins' code is the difference and what is the flag in citeproc.js that controls which method is used?

**Comment by fbennett** [comment]
That would be terrific. Making the following change to processor source (as `CSL`) before instantiation will toggle on capitalization of subtitles:
``` javascript
CSL.development_extensions.main_title_from_short_title = true;
CSL.development_extensions.uppercase_subtitles = true;
```

**Comment by bwiernik** [comment]
I submitted a pull request to merge the two versions with a toggle to change the settings. It currently requires a restart to change the setting.

**Comment by fbennett** [comment]
Will get to it soon I hope!
