### ISSUE TITLE
Problem with starting up Zotero after installing propachi

### ISSUE THREAD

**Issue by sdspieg** [Juris-M/propachi-vanilla#5]
I accidentally installed a wrong plugin (propachi-vanilla) and Zotero now doesn't boot anymore. Any idea how I could restart it without add-ons? Or any other solution? 
`[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIAppShellService.hiddenDOMWindow]" nsresult: "0x80004005 (NS_ERROR_FAILURE)" location: "JS frame :: chrome://zotero/content/xpcom/zotero.js :: this.init< :: line 219" data: no]
this.init<@chrome://zotero/content/xpcom/zotero.js:219:13
From previous event:
ZoteroService@file:///C:/Program%20Files%20(x86)/Zotero/components/zotero-service.js:347:4
installProcessor<@resource://gre/modules/addons/XPIProvider.jsm -> file:///C:/Users/sdspi/AppData/Roaming/Zotero/Zotero/Profiles/l82w2qou.default/extensions/propachi-vanilla@juris-m.github.io/bootstrap.js:47:14
prefObserver.observe@resource://gre/modules/addons/XPIProvider.jsm -> file:///C:/Users/sdspi/AppData/Roaming/Zotero/Zotero/Profiles/l82w2qou.default/extensions/propachi-vanilla@juris-m.github.io/bootstrap.js:102:9
setDefaultPrefs@resource://gre/modules/addons/XPIProvider.jsm -> file:///C:/Users/sdspi/AppData/Roaming/Zotero/Zotero/Profiles/l82w2qou.default/extensions/propachi-vanilla@juris-m.github.io/bootstrap.js:34:9
startup@resource://gre/modules/addons/XPIProvider.jsm -> file:///C:/Users/sdspi/AppData/Roaming/Zotero/Zotero/Profiles/l82w2qou.default/extensions/propachi-vanilla@juris-m.github.io/bootstrap.js:114:5
this.XPIProvider.callBootstrapMethod@resource://gre/modules/addons/XPIProvider.jsm:4968:9
this.XPIProvider.startup@resource://gre/modules/addons/XPIProvider.jsm:2885:13
callProvider@resource://gre/modules/AddonManager.jsm:237:12
_startProvider@resource://gre/modules/AddonManager.jsm:790:5
AddonManagerInternal.startup@resource://gre/modules/AddonManager.jsm:976:9
this.AddonManagerPrivate.startup@resource://gre/modules/AddonManager.jsm:3033:5
amManager.prototype.observe@resource://gre/components/addonManager.js:65:9`

**Comment by fbennett** [comment]
Do you get this error with the current version of the plugin? There was a bug that triggered this crash, but I'm pretty sure that the current release will run without error.
