### ISSUE TITLE
End of life

### ISSUE THREAD

**Issue by bwiernik** [Juris-M/propachi-vanilla#7]
Did I read correctly that that intention is to end-of-life the propachi plugin? With Zotero automatically setting the uppercase flag for APA styles, I don’t see much of an issue with that (haven’t tested Zotero’s behavior and how it handles dependent styles, etc.).

Should we set an update to disable the plugin for current users?

**Comment by fbennett** [comment]
Yes, and no. Yes, in that the download link is already gone. No, in that it doesn't update automatically, so users will need to remove it on their own.

(if I'm wrong on the latter and it can somehow be disabled automatically, would be happy to take a pull request.)
